# Generated by Django 2.0.5 on 2018-05-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('barcode', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('state', models.CharField(choices=[('AC', 'Active'), ('RV', 'Revoked')], default='AC', max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kdv.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('AC', 'Active'), ('CH', 'Challenged'), ('RT', 'Returned')], default='AC', max_length=2)),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set_out', to='kdv.Account')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set_in', to='kdv.Account')),
            ],
        ),
    ]
